### PR TITLE
Chimoney Rust SDK: Initial Implementation and API Integration

### PR DESCRIPTION
**Pull request by Cyber-Freak999**
This pull request introduces the initial implementation of the Chimoney Rust SDK. It includes:

- File structure: A well-organized file structure for the SDK, separating core functionalities and models.
- API functionalities: Implementation of key Chimoney API functionalities, including account management, transaction retrieval, and transfers.
- Models: Defined models for representing Chimoney entities like accounts, transactions, and users.
- Account module: Dedicated module for managing account-related functionalities.

This initial implementation provides a solid foundation for further development and integration.

Additional notes:
- Other modules are yet to be added.
- Unit tests are not yet implemented but will be added in subsequent pull requests.
- Documentation is currently limited but will be expanded as the SDK matures.

### CODE REVIEW

**Comment by Cyber-Freak999** [comment]
@phyleria @victorcodess

**Comment by phyleria** [comment]
Thanks @Cyber-Freak999 

We'll review this promptly

**Comment by phyleria** [comment]
Kindly review @uchibeke

**Review by uchibeke — APPROVED** [review]
LGTM ♠️

**Pull request merged**
